// Журнал учеников для валидации
export const STUDENTS_LIST = [
  { firstName: 'Дмитро', lastName: 'Брусінський' },
  { firstName: 'Поліна', lastName: 'Гайдай' },
  { firstName: 'Богдан', lastName: 'Дубановський' },
  { firstName: 'Сергій', lastName: 'Жидков' },
  { firstName: 'Олександр', lastName: 'Зелінський' },
  { firstName: 'Тимур', lastName: 'Капустін' },
  { firstName: 'Арсеній', lastName: 'Неділько' },
  { firstName: 'Роман', lastName: 'Пантелєєв' },
  { firstName: 'Філіпп', lastName: 'Поварнін' },
  { firstName: 'Олександра', lastName: 'Поліщук' },
  { firstName: 'Микита', lastName: 'Рябуха' },
  { firstName: 'Данило', lastName: 'Рязанцев' },
  { firstName: 'Віра', lastName: 'Сахно' },
  { firstName: 'Олег', lastName: 'Сорока' },
  { firstName: 'Аріна', lastName: 'Хабазня' },
  { firstName: 'Данило', lastName: 'Цурпаль' },
  { firstName: 'Микита', lastName: 'Чувал' },
  { firstName: 'Мама', lastName: 'Габена' },
  { firstName: 'Джеффри', lastName: 'Эптштейн' },
  { firstName: 'Данило', lastName: 'Колбасєнко' },
];
